language: generic 
sudo: required
services: 
  - docker 

before_install:
  - docker build -t vsharma310/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true vsharma310/docker-react npm run test
